[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "test"
version = "0.0.0"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-alpha6"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-alpha6"


